
apiVersion: v1

kind: Service

metadata:

  name: odoo-service

  namespace: {{ .Values.namespace }}

  labels:

    {{- include "odoo.labels" . | nindent 4 }}

spec:

  selector:

    {{- include "odoo.selectorLabels" . | nindent 4 }}

  type: {{ .Values.service.type }}

  ports:

    - name: http

      port: {{ .Values.service.httpPort }}

      targetPort: {{ .Values.service.targetPort }}

      protocol: TCP

    - name: longpolling

      port: {{ .Values.service.longpollingPort }}

      targetPort: {{ .Values.service.longpollingPort }}

      protocol: TCP

